# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Add Binaries to Release

on: push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: remove old files
        run: rm -rf Linux Darwin
      - name: Download a linix file
        if: startsWith(github.ref, 'refs/tags/')
        uses: carlosperate/download-file-action@v1.0.3
        with:
            file-url: 'http://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Linux/master/6196ca7631f524a61c50476f9110ce130f47211e/near-vm-runner-standalone'
            file-name: 'near-vm-runner-standalone'
            location: './Linux/Linux'
      - name: Download a mac file
        if: startsWith(github.ref, 'refs/tags/')
        uses: carlosperate/download-file-action@v1.0.3
        with:
            file-url: 'http://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Darwin/master/6196ca7631f524a61c50476f9110ce130f47211e/near-vm-runner-standalone'
            file-name: 'near-vm-runner-standalone'
            location: './Darwin/Darwin'
      - name:  Make Executable
        if: startsWith(github.ref, 'refs/tags/')
        run: chmod +x Linux/Linux/near-vm-runner-standalone && chmod +x Darwin/Darwin/near-vm-runner-standalone
      - name:  Tar linux file
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -C Linux -czvf Linux.tar.gz Linux
      - name:  Tar macos file
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -C Darwin -czvf Darwin.tar.gz Darwin
      - name: Release Linux
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: Linux.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: fnkr/github-action-ghr@v1
      - name: Release Macos
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: Darwin.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: fnkr/github-action-ghr@v1
